/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppBillsRouteImport } from './routes/_app/bills'
import { Route as AppForecastRouteImport } from './routes/_app/forecast'
import { Route as AppHealthRouteImport } from './routes/_app/health'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppSavingsRouteImport } from './routes/_app/savings'
import { Route as AppSettingsRouteRouteImport } from './routes/_app/settings/route'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsAccountRouteImport } from './routes/_app/settings/account'
import { Route as AppSettingsAlertsRouteImport } from './routes/_app/settings/alerts'
import { Route as AppSettingsBillingRouteImport } from './routes/_app/settings/billing'
import { Route as AppSettingsImportRouteImport } from './routes/_app/settings/import'
import { Route as AppSettingsSystemRouteImport } from './routes/_app/settings/system'
import { Route as AppSettingsTariffsRouteImport } from './routes/_app/settings/tariffs'
import { Route as AppTeslaIndexRouteImport } from './routes/_app/tesla/index'
import { Route as AppTeslaSetupRouteImport } from './routes/_app/tesla/setup'
import { Route as AppSettingsIntegrationsIndexRouteImport } from './routes/_app/settings/integrations/index'
import { Route as AppSettingsIntegrationsAmberRouteImport } from './routes/_app/settings/integrations/amber'
import { Route as AppSettingsIntegrationsWeatherRouteImport } from './routes/_app/settings/integrations/weather'
import { Route as AppSettingsIntegrationsSungrowIndexRouteImport } from './routes/_app/settings/integrations/sungrow/index'
import { Route as AppSettingsIntegrationsSungrowRoleRouteImport } from './routes/_app/settings/integrations/sungrow/$role'
import { Route as AppSettingsIntegrationsSungrowConnectRouteImport } from './routes/_app/settings/integrations/sungrow/connect'
import { Route as AppSettingsIntegrationsSungrowImportRouteImport } from './routes/_app/settings/integrations/sungrow/import'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsRoute = AppBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AppRoute,
} as any)
const AppForecastRoute = AppForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthRoute = AppHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppSavingsRoute = AppSavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsAlertsRoute = AppSettingsAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsImportRoute = AppSettingsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsSystemRoute = AppSettingsSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsTariffsRoute = AppSettingsTariffsRouteImport.update({
  id: '/tariffs',
  path: '/tariffs',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppTeslaIndexRoute = AppTeslaIndexRouteImport.update({
  id: '/tesla/',
  path: '/tesla/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeslaSetupRoute = AppTeslaSetupRouteImport.update({
  id: '/tesla/setup',
  path: '/tesla/setup',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIntegrationsIndexRoute =
  AppSettingsIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppSettingsIntegrationsAmberRoute =
  AppSettingsIntegrationsAmberRouteImport.update({
    id: '/integrations/amber',
    path: '/integrations/amber',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppSettingsIntegrationsWeatherRoute =
  AppSettingsIntegrationsWeatherRouteImport.update({
    id: '/integrations/weather',
    path: '/integrations/weather',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppSettingsIntegrationsSungrowIndexRoute =
  AppSettingsIntegrationsSungrowIndexRouteImport.update({
    id: '/integrations/sungrow/',
    path: '/integrations/sungrow/',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppSettingsIntegrationsSungrowRoleRoute =
  AppSettingsIntegrationsSungrowRoleRouteImport.update({
    id: '/integrations/sungrow/$role',
    path: '/integrations/sungrow/$role',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppSettingsIntegrationsSungrowConnectRoute =
  AppSettingsIntegrationsSungrowConnectRouteImport.update({
    id: '/integrations/sungrow/connect',
    path: '/integrations/sungrow/connect',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppSettingsIntegrationsSungrowImportRoute =
  AppSettingsIntegrationsSungrowImportRouteImport.update({
    id: '/integrations/sungrow/import',
    path: '/integrations/sungrow/import',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/settings': typeof AppSettingsRouteRouteWithChildren
  '/bills': typeof AppBillsRoute
  '/forecast': typeof AppForecastRoute
  '/health': typeof AppHealthRoute
  '/history': typeof AppHistoryRoute
  '/insights': typeof AppInsightsRoute
  '/savings': typeof AppSavingsRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/alerts': typeof AppSettingsAlertsRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/import': typeof AppSettingsImportRoute
  '/settings/system': typeof AppSettingsSystemRoute
  '/settings/tariffs': typeof AppSettingsTariffsRoute
  '/tesla/setup': typeof AppTeslaSetupRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/tesla/': typeof AppTeslaIndexRoute
  '/settings/integrations/amber': typeof AppSettingsIntegrationsAmberRoute
  '/settings/integrations/weather': typeof AppSettingsIntegrationsWeatherRoute
  '/settings/integrations/': typeof AppSettingsIntegrationsIndexRoute
  '/settings/integrations/sungrow/$role': typeof AppSettingsIntegrationsSungrowRoleRoute
  '/settings/integrations/sungrow/connect': typeof AppSettingsIntegrationsSungrowConnectRoute
  '/settings/integrations/sungrow/import': typeof AppSettingsIntegrationsSungrowImportRoute
  '/settings/integrations/sungrow/': typeof AppSettingsIntegrationsSungrowIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/bills': typeof AppBillsRoute
  '/forecast': typeof AppForecastRoute
  '/health': typeof AppHealthRoute
  '/history': typeof AppHistoryRoute
  '/insights': typeof AppInsightsRoute
  '/savings': typeof AppSavingsRoute
  '/': typeof AppIndexRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/alerts': typeof AppSettingsAlertsRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/import': typeof AppSettingsImportRoute
  '/settings/system': typeof AppSettingsSystemRoute
  '/settings/tariffs': typeof AppSettingsTariffsRoute
  '/tesla/setup': typeof AppTeslaSetupRoute
  '/settings': typeof AppSettingsIndexRoute
  '/tesla': typeof AppTeslaIndexRoute
  '/settings/integrations/amber': typeof AppSettingsIntegrationsAmberRoute
  '/settings/integrations/weather': typeof AppSettingsIntegrationsWeatherRoute
  '/settings/integrations': typeof AppSettingsIntegrationsIndexRoute
  '/settings/integrations/sungrow/$role': typeof AppSettingsIntegrationsSungrowRoleRoute
  '/settings/integrations/sungrow/connect': typeof AppSettingsIntegrationsSungrowConnectRoute
  '/settings/integrations/sungrow/import': typeof AppSettingsIntegrationsSungrowImportRoute
  '/settings/integrations/sungrow': typeof AppSettingsIntegrationsSungrowIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/_app/settings': typeof AppSettingsRouteRouteWithChildren
  '/_app/bills': typeof AppBillsRoute
  '/_app/forecast': typeof AppForecastRoute
  '/_app/health': typeof AppHealthRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/savings': typeof AppSavingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/alerts': typeof AppSettingsAlertsRoute
  '/_app/settings/billing': typeof AppSettingsBillingRoute
  '/_app/settings/import': typeof AppSettingsImportRoute
  '/_app/settings/system': typeof AppSettingsSystemRoute
  '/_app/settings/tariffs': typeof AppSettingsTariffsRoute
  '/_app/tesla/setup': typeof AppTeslaSetupRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/tesla/': typeof AppTeslaIndexRoute
  '/_app/settings/integrations/amber': typeof AppSettingsIntegrationsAmberRoute
  '/_app/settings/integrations/weather': typeof AppSettingsIntegrationsWeatherRoute
  '/_app/settings/integrations/': typeof AppSettingsIntegrationsIndexRoute
  '/_app/settings/integrations/sungrow/$role': typeof AppSettingsIntegrationsSungrowRoleRoute
  '/_app/settings/integrations/sungrow/connect': typeof AppSettingsIntegrationsSungrowConnectRoute
  '/_app/settings/integrations/sungrow/import': typeof AppSettingsIntegrationsSungrowImportRoute
  '/_app/settings/integrations/sungrow/': typeof AppSettingsIntegrationsSungrowIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/welcome'
    | '/settings'
    | '/bills'
    | '/forecast'
    | '/health'
    | '/history'
    | '/insights'
    | '/savings'
    | '/settings/account'
    | '/settings/alerts'
    | '/settings/billing'
    | '/settings/import'
    | '/settings/system'
    | '/settings/tariffs'
    | '/tesla/setup'
    | '/settings/'
    | '/tesla/'
    | '/settings/integrations/amber'
    | '/settings/integrations/weather'
    | '/settings/integrations/'
    | '/settings/integrations/sungrow/$role'
    | '/settings/integrations/sungrow/connect'
    | '/settings/integrations/sungrow/import'
    | '/settings/integrations/sungrow/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/welcome'
    | '/bills'
    | '/forecast'
    | '/health'
    | '/history'
    | '/insights'
    | '/savings'
    | '/'
    | '/settings/account'
    | '/settings/alerts'
    | '/settings/billing'
    | '/settings/import'
    | '/settings/system'
    | '/settings/tariffs'
    | '/tesla/setup'
    | '/settings'
    | '/tesla'
    | '/settings/integrations/amber'
    | '/settings/integrations/weather'
    | '/settings/integrations'
    | '/settings/integrations/sungrow/$role'
    | '/settings/integrations/sungrow/connect'
    | '/settings/integrations/sungrow/import'
    | '/settings/integrations/sungrow'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/welcome'
    | '/_app/settings'
    | '/_app/bills'
    | '/_app/forecast'
    | '/_app/health'
    | '/_app/history'
    | '/_app/insights'
    | '/_app/savings'
    | '/_app/'
    | '/_app/settings/account'
    | '/_app/settings/alerts'
    | '/_app/settings/billing'
    | '/_app/settings/import'
    | '/_app/settings/system'
    | '/_app/settings/tariffs'
    | '/_app/tesla/setup'
    | '/_app/settings/'
    | '/_app/tesla/'
    | '/_app/settings/integrations/amber'
    | '/_app/settings/integrations/weather'
    | '/_app/settings/integrations/'
    | '/_app/settings/integrations/sungrow/$role'
    | '/_app/settings/integrations/sungrow/connect'
    | '/_app/settings/integrations/sungrow/import'
    | '/_app/settings/integrations/sungrow/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bills': {
      id: '/_app/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof AppBillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forecast': {
      id: '/_app/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof AppForecastRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/health': {
      id: '/_app/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AppHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/savings': {
      id: '/_app/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof AppSavingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/alerts': {
      id: '/_app/settings/alerts'
      path: '/alerts'
      fullPath: '/settings/alerts'
      preLoaderRoute: typeof AppSettingsAlertsRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/billing': {
      id: '/_app/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/import': {
      id: '/_app/settings/import'
      path: '/import'
      fullPath: '/settings/import'
      preLoaderRoute: typeof AppSettingsImportRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/system': {
      id: '/_app/settings/system'
      path: '/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof AppSettingsSystemRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/tariffs': {
      id: '/_app/settings/tariffs'
      path: '/tariffs'
      fullPath: '/settings/tariffs'
      preLoaderRoute: typeof AppSettingsTariffsRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/tesla/': {
      id: '/_app/tesla/'
      path: '/tesla'
      fullPath: '/tesla/'
      preLoaderRoute: typeof AppTeslaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tesla/setup': {
      id: '/_app/tesla/setup'
      path: '/tesla/setup'
      fullPath: '/tesla/setup'
      preLoaderRoute: typeof AppTeslaSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/integrations/': {
      id: '/_app/settings/integrations/'
      path: '/integrations'
      fullPath: '/settings/integrations/'
      preLoaderRoute: typeof AppSettingsIntegrationsIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/integrations/amber': {
      id: '/_app/settings/integrations/amber'
      path: '/integrations/amber'
      fullPath: '/settings/integrations/amber'
      preLoaderRoute: typeof AppSettingsIntegrationsAmberRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/integrations/weather': {
      id: '/_app/settings/integrations/weather'
      path: '/integrations/weather'
      fullPath: '/settings/integrations/weather'
      preLoaderRoute: typeof AppSettingsIntegrationsWeatherRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/integrations/sungrow/': {
      id: '/_app/settings/integrations/sungrow/'
      path: '/integrations/sungrow'
      fullPath: '/settings/integrations/sungrow/'
      preLoaderRoute: typeof AppSettingsIntegrationsSungrowIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/integrations/sungrow/$role': {
      id: '/_app/settings/integrations/sungrow/$role'
      path: '/integrations/sungrow/$role'
      fullPath: '/settings/integrations/sungrow/$role'
      preLoaderRoute: typeof AppSettingsIntegrationsSungrowRoleRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/integrations/sungrow/connect': {
      id: '/_app/settings/integrations/sungrow/connect'
      path: '/integrations/sungrow/connect'
      fullPath: '/settings/integrations/sungrow/connect'
      preLoaderRoute: typeof AppSettingsIntegrationsSungrowConnectRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/integrations/sungrow/import': {
      id: '/_app/settings/integrations/sungrow/import'
      path: '/integrations/sungrow/import'
      fullPath: '/settings/integrations/sungrow/import'
      preLoaderRoute: typeof AppSettingsIntegrationsSungrowImportRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
  }
}

interface AppSettingsRouteRouteChildren {
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsAlertsRoute: typeof AppSettingsAlertsRoute
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsImportRoute: typeof AppSettingsImportRoute
  AppSettingsSystemRoute: typeof AppSettingsSystemRoute
  AppSettingsTariffsRoute: typeof AppSettingsTariffsRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSettingsIntegrationsAmberRoute: typeof AppSettingsIntegrationsAmberRoute
  AppSettingsIntegrationsWeatherRoute: typeof AppSettingsIntegrationsWeatherRoute
  AppSettingsIntegrationsIndexRoute: typeof AppSettingsIntegrationsIndexRoute
  AppSettingsIntegrationsSungrowRoleRoute: typeof AppSettingsIntegrationsSungrowRoleRoute
  AppSettingsIntegrationsSungrowConnectRoute: typeof AppSettingsIntegrationsSungrowConnectRoute
  AppSettingsIntegrationsSungrowImportRoute: typeof AppSettingsIntegrationsSungrowImportRoute
  AppSettingsIntegrationsSungrowIndexRoute: typeof AppSettingsIntegrationsSungrowIndexRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsAlertsRoute: AppSettingsAlertsRoute,
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsImportRoute: AppSettingsImportRoute,
  AppSettingsSystemRoute: AppSettingsSystemRoute,
  AppSettingsTariffsRoute: AppSettingsTariffsRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSettingsIntegrationsAmberRoute: AppSettingsIntegrationsAmberRoute,
  AppSettingsIntegrationsWeatherRoute: AppSettingsIntegrationsWeatherRoute,
  AppSettingsIntegrationsIndexRoute: AppSettingsIntegrationsIndexRoute,
  AppSettingsIntegrationsSungrowRoleRoute:
    AppSettingsIntegrationsSungrowRoleRoute,
  AppSettingsIntegrationsSungrowConnectRoute:
    AppSettingsIntegrationsSungrowConnectRoute,
  AppSettingsIntegrationsSungrowImportRoute:
    AppSettingsIntegrationsSungrowImportRoute,
  AppSettingsIntegrationsSungrowIndexRoute:
    AppSettingsIntegrationsSungrowIndexRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppRouteChildren {
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppBillsRoute: typeof AppBillsRoute
  AppForecastRoute: typeof AppForecastRoute
  AppHealthRoute: typeof AppHealthRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppSavingsRoute: typeof AppSavingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTeslaSetupRoute: typeof AppTeslaSetupRoute
  AppTeslaIndexRoute: typeof AppTeslaIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppBillsRoute: AppBillsRoute,
  AppForecastRoute: AppForecastRoute,
  AppHealthRoute: AppHealthRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppSavingsRoute: AppSavingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppTeslaSetupRoute: AppTeslaSetupRoute,
  AppTeslaIndexRoute: AppTeslaIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
