/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppForecastRouteImport } from './routes/_app/forecast'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppSavingsRouteImport } from './routes/_app/savings'
import { Route as AppSettingsRouteRouteImport } from './routes/_app/settings/route'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsAccountRouteImport } from './routes/_app/settings/account'
import { Route as AppSettingsIntegrationsRouteImport } from './routes/_app/settings/integrations'
import { Route as AppSettingsSystemRouteImport } from './routes/_app/settings/system'
import { Route as AppSettingsTariffsRouteImport } from './routes/_app/settings/tariffs'
import { Route as AppTeslaIndexRouteImport } from './routes/_app/tesla/index'
import { Route as AppTeslaSetupRouteImport } from './routes/_app/tesla/setup'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppForecastRoute = AppForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppSavingsRoute = AppSavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsIntegrationsRoute = AppSettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsSystemRoute = AppSettingsSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsTariffsRoute = AppSettingsTariffsRouteImport.update({
  id: '/tariffs',
  path: '/tariffs',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppTeslaIndexRoute = AppTeslaIndexRouteImport.update({
  id: '/tesla/',
  path: '/tesla/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeslaSetupRoute = AppTeslaSetupRouteImport.update({
  id: '/tesla/setup',
  path: '/tesla/setup',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof AppSettingsRouteRouteWithChildren
  '/forecast': typeof AppForecastRoute
  '/history': typeof AppHistoryRoute
  '/insights': typeof AppInsightsRoute
  '/savings': typeof AppSavingsRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/settings/system': typeof AppSettingsSystemRoute
  '/settings/tariffs': typeof AppSettingsTariffsRoute
  '/tesla/setup': typeof AppTeslaSetupRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/tesla/': typeof AppTeslaIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/forecast': typeof AppForecastRoute
  '/history': typeof AppHistoryRoute
  '/insights': typeof AppInsightsRoute
  '/savings': typeof AppSavingsRoute
  '/': typeof AppIndexRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/settings/system': typeof AppSettingsSystemRoute
  '/settings/tariffs': typeof AppSettingsTariffsRoute
  '/tesla/setup': typeof AppTeslaSetupRoute
  '/settings': typeof AppSettingsIndexRoute
  '/tesla': typeof AppTeslaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/settings': typeof AppSettingsRouteRouteWithChildren
  '/_app/forecast': typeof AppForecastRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/savings': typeof AppSavingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/_app/settings/system': typeof AppSettingsSystemRoute
  '/_app/settings/tariffs': typeof AppSettingsTariffsRoute
  '/_app/tesla/setup': typeof AppTeslaSetupRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/tesla/': typeof AppTeslaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/forecast'
    | '/history'
    | '/insights'
    | '/savings'
    | '/settings/account'
    | '/settings/integrations'
    | '/settings/system'
    | '/settings/tariffs'
    | '/tesla/setup'
    | '/settings/'
    | '/tesla/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/forecast'
    | '/history'
    | '/insights'
    | '/savings'
    | '/'
    | '/settings/account'
    | '/settings/integrations'
    | '/settings/system'
    | '/settings/tariffs'
    | '/tesla/setup'
    | '/settings'
    | '/tesla'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/settings'
    | '/_app/forecast'
    | '/_app/history'
    | '/_app/insights'
    | '/_app/savings'
    | '/_app/'
    | '/_app/settings/account'
    | '/_app/settings/integrations'
    | '/_app/settings/system'
    | '/_app/settings/tariffs'
    | '/_app/tesla/setup'
    | '/_app/settings/'
    | '/_app/tesla/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forecast': {
      id: '/_app/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof AppForecastRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/savings': {
      id: '/_app/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof AppSavingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/integrations': {
      id: '/_app/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AppSettingsIntegrationsRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/system': {
      id: '/_app/settings/system'
      path: '/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof AppSettingsSystemRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/tariffs': {
      id: '/_app/settings/tariffs'
      path: '/tariffs'
      fullPath: '/settings/tariffs'
      preLoaderRoute: typeof AppSettingsTariffsRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/tesla/': {
      id: '/_app/tesla/'
      path: '/tesla'
      fullPath: '/tesla/'
      preLoaderRoute: typeof AppTeslaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tesla/setup': {
      id: '/_app/tesla/setup'
      path: '/tesla/setup'
      fullPath: '/tesla/setup'
      preLoaderRoute: typeof AppTeslaSetupRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppSettingsRouteRouteChildren {
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsIntegrationsRoute: typeof AppSettingsIntegrationsRoute
  AppSettingsSystemRoute: typeof AppSettingsSystemRoute
  AppSettingsTariffsRoute: typeof AppSettingsTariffsRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsIntegrationsRoute: AppSettingsIntegrationsRoute,
  AppSettingsSystemRoute: AppSettingsSystemRoute,
  AppSettingsTariffsRoute: AppSettingsTariffsRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppRouteChildren {
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppForecastRoute: typeof AppForecastRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppSavingsRoute: typeof AppSavingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTeslaSetupRoute: typeof AppTeslaSetupRoute
  AppTeslaIndexRoute: typeof AppTeslaIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppForecastRoute: AppForecastRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppSavingsRoute: AppSavingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppTeslaSetupRoute: AppTeslaSetupRoute,
  AppTeslaIndexRoute: AppTeslaIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
